export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_ERR = "ADMIN_REGISTER_ERR";

//login
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERR = "ADMIN_LOGIN_ERR";

//AdminTaskAsign
export const ADMIN_TASK_ASIGN_REQUEST = "ADMIN_TASK_ASIGN_REQUEST";
export const ADMIN_TASK_ASIGN_SUCCESS = "ADMIN_TASK_ASIGN_SUCCESS";
export const ADMIN_TASK_ASIGN_ERR = "ADMIN_TASK_ASIGN_ERR";

//AdminTaskAsignOne
export const ADMIN_TASK_ASIGN_ONE_REQUEST = "ADMIN_TASK_ASIGN_ONE_REQUEST";
export const ADMIN_TASK_ASIGN_ONE_SUCCESS = "ADMIN_TASK_ASIGN_ONE_SUCCESS";
export const ADMIN_TASK_ASIGN_ONE_ERR = "ADMIN_TASK_ASIGN_ONE_ERR";

//AdminTaskAsign
export const ADMIN_TASK_ASIGN_FIND_REQUEST = "ADMIN_TASK_ASIGN_FIND_REQUEST";
export const ADMIN_TASK_ASIGN_FIND_SUCCESS = "ADMIN_TASK_ASIGN_FIND_SUCCESS";
export const ADMIN_TASK_ASIGN_FIND_ERR = "ADMIN_TASK_ASIGN_FIND_ERR";

//AdminTaskAsignProject
export const ADMIN_TASK_ASIGN_PROJECT_FIND_REQUEST =
  "ADMIN_TASK_ASIGN_PROJECT_FIND_REQUEST";
export const ADMIN_TASK_ASIGN_PROJECT_FIND_SUCCESS =
  "ADMIN_TASK_ASIGN_PROJECT_FIND_SUCCESS";
export const ADMIN_TASK_ASIGN_PROJECT_FIND_ERR =
  "ADMIN_TASK_ASIGN_PROJECT_FIND_ERR";

//AdminTaskAsignStatusChang
export const ADMIN_TASK_ASIGN_STATUS_CHANGE_REQUEST =
  "ADMIN_TASK_ASIGN_STATUS_CHANGE_REQUEST";
export const ADMIN_TASK_ASIGN_STATUS_CHANGE_SUCCESS =
  "ADMIN_TASK_ASIGN_STATUS_CHANGE_SUCCESS";
export const ADMIN_TASK_ASIGN_STATUS_CHANGE_ERR =
  "ADMIN_TASK_ASIGN_STATUS_CHANGE_ERR";

//AdminuserFind
export const ADMIN_USER_FIND_REQUEST = "ADMIN_USER_FIND_REQUEST";
export const ADMIN_USER_FIND_SUCCESS = "ADMIN_USER_FIND_SUCCESS";
export const ADMIN_USER_FIND_ERR = "ADMIN_USER_FIND_ERR";

//AdminuserFindForAsignTask
export const ADMIN_USER_FIND_FOR_ASIGN_REQUEST =
  "ADMIN_USER_FIND_FOR_ASIGN_REQUEST";
export const ADMIN_USER_FIND_FOR_ASIGN_SUCCESS =
  "ADMIN_USER_FIND_FOR_ASIGN_SUCCESS";
export const ADMIN_USER_FIND_FOR_ASIGN_ERR = "ADMIN_USER_FIND_FOR_ASIGN_ERR";

//UserRegister
export const ADMIN_USER_REGISTER_REQUEST = "ADMIN_USER_REGISTER_REQUEST";
export const ADMIN_USER_REGISTER_SUCCESS = "ADMIN_USER_REGISTER_SUCCESS";
export const ADMIN_USER_REGISTER_ERR = "ADMIN_USER_REGISTER_ERR";

//userStatusChange
export const ADMIN_USER_STATUS_CHANGE_REQUEST =
  "ADMIN_USER_STATUS_CHANGE_REQUEST";
export const ADMIN_USER_STATUS_CHANGE_SUCCESS =
  "ADMIN_USER_STATUS_CHANGE_SUCCESS";
export const ADMIN_USER_STATUS_CHANGE_ERR = "ADMIN_USER_STATUS_CHANGE_ERR";

//DELETE PROJECT
export const ADMIN_DELETE_PROJECT_REQUEST = "ADMIN_DELETE_PROJECT_REQUEST";
export const ADMIN_DELETE_PROJECT_SUCCESS = "ADMIN_DELETE_PROJECT_SUCCESS";
export const ADMIN_DELETE_PROJECT_ERR = "ADMIN_DELETE_PROJECT_ERR";

//user Rate Decrement
export const USER_RATE_DECREASE_REQUEST = "USER_RATE_DECREASE_REQUEST";
export const USER_RATE_DECREASE_SUCCESS = "USER_RATE_DECREASE_SUCCESS";
export const USER_RATE_DECREASE_ERR = "USER_RATE_DECREASE_ERR";

//user Rate Increment
export const USER_RATE_INCREASE_REQUEST = "USER_RATE_INCREASE_REQUEST";
export const USER_RATE_INCREASE_SUCCESS = "USER_RATE_INCREASE_SUCCESS";
export const USER_RATE_INCREASE_ERR = "USER_RATE_INCREASE_ERR";

//admin Task Content
export const ADMIN_TASK_CONTENT_REQUEST = "ADMIN_TASK_CONTENT_REQUEST";
export const ADMIN_TASK_CONTENT_SUCCESS = "ADMIN_TASK_CONTENT_SUCCESS";
export const ADMIN_TASK_CONTENT_ERR = "ADMIN_TASK_CONTENT_ERR";

//admin Task Content FIND
export const ADMIN_TASK_CONTENT_FIND_REQUEST =
  "ADMIN_TASK_CONTENT_FIND_REQUEST";
export const ADMIN_TASK_CONTENT_FIND_SUCCESS =
  "ADMIN_TASK_CONTENT_FIND_SUCCESS";
export const ADMIN_TASK_CONTENT_FIND_ERR = "ADMIN_TASK_CONTENT_FIND_ERR";

//admin Task Content FIND
export const ADMIN_TASK_CONTENT_DELETE_REQUEST =
  "ADMIN_TASK_CONTENT_DELETE_REQUEST";
export const ADMIN_TASK_CONTENT_DELETE_SUCCESS =
  "ADMIN_TASK_CONTENT_DELETE_SUCCESS";
export const ADMIN_TASK_CONTENT_DELETE_ERR = "ADMIN_TASK_CONTENT_DELETE_ERR";

//admin ExcelSheet
export const ADMIN_EXCEL_SHEET_REQUEST = "ADMIN_EXCEL_SHEET_REQUEST";
export const ADMIN_EXCEL_SHEET_SUCCESS = "ADMIN_EXCEL_SHEET_SUCCESS";
export const ADMIN_EXCEL_SHEET_ERR = "ADMIN_EXCEL_SHEET_ERR";

//admin ExcelSheet
export const ADMIN_EXCEL_SHEET_RESOURCE_FIND_REQUEST = "ADMIN_EXCEL_SHEET_RESOURCE_FIND_REQUEST";
export const ADMIN_EXCEL_SHEET_RESOURCE_FIND_SUCCESS = "ADMIN_EXCEL_SHEET_RESOURCE_FIND_SUCCESS";
export const ADMIN_EXCEL_SHEET_RESOURCE_FIND_ERR = "ADMIN_EXCEL_SHEET_RESOURCE_FIND_ERR";

//admin ExcelSheet
export const ADMIN_EXCEL_SHEET_EXPENSES_FIND_REQUEST = "ADMIN_EXCEL_SHEET_EXPENSES_FIND_REQUEST";
export const ADMIN_EXCEL_SHEET_EXPENSES_FIND_SUCCESS = "ADMIN_EXCEL_SHEET_EXPENSES_FIND_SUCCESS";
export const ADMIN_EXCEL_SHEET_EXPENSES_FIND_ERR = "ADMIN_EXCEL_SHEET_EXPENSES_FIND_ERR";

//admin ExcelSheet
export const ADMIN_EXCEL_SHEET_CASH_FLOW_FIND_REQUEST = "ADMIN_EXCEL_SHEET_CASH_FLOW_FIND_REQUEST";
export const ADMIN_EXCEL_SHEET_CASH_FLOW_FIND_SUCCESS = "ADMIN_EXCEL_SHEET_CASH_FLOW_FIND_SUCCESS";
export const ADMIN_EXCEL_SHEET_CASH_FLOW_FIND_ERR = "ADMIN_EXCEL_SHEET_CASH_FLOW_FIND_ERR";
