export const USER_TASK_FIND_REQUEST = "USER_TASK_FIND_REQUEST";
export const USER_TASK_FIND_SUCCESS = "USER_TASK_FIND_SUCCESS";
export const USER_TASK_FIND_ERR = "USER_TASK_FIND_ERR";

//userTask Change
export const USER_TASK_STATUS_CHANGE_REQUEST =
  "USER_TASK_STATUS_CHANGE_REQUEST";
export const USER_TASK_STATUS_CHANGE_SUCCESS =
  "USER_TASK_STATUS_CHANGE_SUCCESS";
export const USER_TASK_STATUS_CHANGE_ERR = "USER_TASK_STATUS_CHANGE_ERR";

// /userTask Change
export const USER_FIND_REQUEST = "USER_FIND_REQUEST";
export const USER_FIND_SUCCESS = "USER_FIND_SUCCESS";
export const USER_FIND_ERR = "USER_FIND_ERR";

// /Edit Form Details
export const EDIT_PROFILE_USER_REQUEST = "EDIT_PROFILE_USER_REQUEST";
export const EDIT_PROFILE_USER_SUCCESS = "EDIT_PROFILE_USER_SUCCESS";
export const EDIT_PROFILE_USER_ERR = "EDIT_PROFILE_USER_ERR";

// Image Upload
export const USER_IMAGE_UPLOAD_REQUEST = "USER_IMAGE_UPLOAD_REQUEST";
export const USER_IMAGE_UPLOAD_SUCCESS = "USER_IMAGE_UPLOAD_SUCCESS";
export const USER_IMAGE_UPLOAD_ERR = "USER_IMAGE_UPLOAD_ERR";